# MAIN

# GRAPHICS
graphics:
  screen_width: 1024
  screen_height: 1024
  fps: 60

# COMBAT
combat:
  qte:
    base_speed: 420
    base_crit_chance: 0.2
    acceleration: 0.0
    green_offset_pct: 0.0
    randomize_offset: true
    random_range: 0.85
    stamina_cost_on_miss: 5      # отдельно от оружия
    bar_width: 520
    bar_height: 48

# ENTITY CONFIGS
enemies_conf: enemies.yaml
items_conf: items.yaml
level_conf: level.yaml
player_conf: player.yaml
